### ISSUE TITLE
Not working with angular 11

### ISSUE THREAD

**Issue by ayoubkhan558** [Brakebein/ngx-tagify#1]
Not working with angular 11

**Comment by Brakebein** [comment]
It would be kind to share more details on what have you tried or what errors you are getting.

I guess you get an error like this:

```
 node_modules/@types/yaireo__tagify/index.d.ts:475:1
    475 export = Tagify;
        ~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

This is due to the `@types/yaireo__tagify` package. Just set the flag mentioned in this error within  `compilerOptions` in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    
    "allowSyntheticDefaultImports": true,
    
  }
}
```

I will update the readme.
