### ISSUE TITLE
Mixed mode withour textarea

### ISSUE THREAD

**Issue by FreshDoktor** [Brakebein/ngx-tagify#10]
Hey is it possible to get a tagify input with mix mode without using a textarea? I searched in your and yairEOs Documentation but can not find anything about it.

**Comment by Brakebein** [comment]
I'm not sure, how you want it to be. Internally, only an `<input>` element is used. But the input or textarea element is hidden by tagify anyway.

If you want tagify single-lined, i.e., looking like an input element instead of a textarea element, have a look at this issue: https://github.com/yairEO/tagify/issues/145

**Comment by FreshDoktor** [comment]
Ahh thanks that helped me a lot!
